Feature/menu
wecode-bootcamp-korea/9-WE_T_S-backend pull request #2
Opened 2020-06-25 12:34 UTC by shrhkddh

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
Menu App 추가
         
		 
## 수정 사항들 자세한 내용
Menu App models.py에 Category, MenuCategory, TypeName, CategoryType Table추가

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-06-25 12:57 UTC, soheon-lee commented on menu/models.py
> +    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
중간테이블 두 속성이 null=True 일 수 없습니다.
한 속성이 존재 하지 않는 다는 것은 중간 테이블에 데이터 자체가 없다는 것입니다.

2020-06-25 13:06 UTC, soheon-lee commented on menu/models.py
> +
마찬가지로 중간 테이블 속성은 nullable 할 수 없습니다.

2020-06-25 13:06 UTC, soheon-lee commented on menu/views.py
> +# Create your views here.
사용하지 않는 코드입니다. 제거해주세요.

2020-06-26 04:23 UTC, evergreen-david requested changes

2020-06-26 04:23 UTC, evergreen-david commented on ami/settings.py
> +	'corsheaders',
```suggestion
    'corsheaders',
```

2020-06-26 04:23 UTC, evergreen-david commented on menu/models.py
> +    category = models.ForeignKey('Category', on_delete=models.CASCADE, default = 1)
default 1 로 설정한 특별한 이유가 있을까요 ? 이렇게하면 의도치않게 새로 상품을 등록할때 1로 될것같아서 말씀드립니다.

2020-06-26 04:58 UTC, evergreen-david approved these changes

2020-06-26 04:58 UTC, merged