[Add]product ListView 와 DetailView 추가
wecode-bootcamp-korea/9-WE_T_S-backend pull request #6
Opened 2020-07-02 02:45 UTC by pjkfckr

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
product 모델에서 ListView 와 DetailView 추가   
         
		 
## 수정 사항들 자세한 내용
ListView에서 db에있는 상품들 색상 별로 출력
DetailView 에서 product_id 와 color_id 를 받아 해당하는 상품을 보여주는 api구성

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-02 07:33 UTC, evergreen-david requested changes

2020-07-02 07:33 UTC, evergreen-david commented on ami/settings.py
> +ALLOWED_HOSTS = ['*', '10.58.1.198', '10.58.1.198:8000']
IP 노출되지않도록 주의해주세요.

2020-07-02 07:33 UTC, evergreen-david commented on ami/urls.py
> +        path('account', include('account.urls')),
들여쓰기 8칸인것같은데 4칸으로 정리 부탁 드립니다.

2020-07-02 07:36 UTC, evergreen-david requested changes

2020-07-02 07:36 UTC, evergreen-david commented on product/views.py
> +                            } for item in product_list]
prefetch 잘 이용해 주셨습니다. 들여쓰기랑 indent 정리 부탁 드릴께요 기본적으로 8칸으로 되어있는것 같은데 정렬 부탁 드립니다.

2020-07-02 07:36 UTC, evergreen-david commented on product/views.py
> +                            } for item in product_list]
정렬예시
```
product_info= [{
    "product_id"     : item.product.id,
    "product_name"   : item.product.name,
    "product_price"  : int(item.product.price),
    "product_color"  : item.color.name,
    "button_colors"  : [colors.color.name for colors in ProductColor.objects.filter(
```

2020-07-02 07:36 UTC, evergreen-david commented on product/views.py
> +                    } for item in product_detail]
위와같이 indent 정렬 부탁 드립니다.

2020-07-02 17:30 UTC, soheon-lee commented on ami/urls.py
> +    path('', include('product.urls')),
서로 다른 두 앱 (menu, product)로 가는 url이 동일합니다. url에 각각 앱 이름을 넣어주시는 것을 추천드립니다.

2020-07-02 17:30 UTC, soheon-lee commented on product/models.py
>      product = models.ManyToManyField('Product', through = 'ProductColor')
간격 정리해주세요.

2020-07-02 17:32 UTC, soheon-lee commented on product/urls.py
> +    path('product/<slug:req_product_id>/color/<slug:req_color_id>', DetailView.as_view()),
앱 url로 오기전 ami/urls.py에 `product`를 미리 정해두시는 것을 추천드립니다 👍

2020-07-02 17:32 UTC, soheon-lee commented on product/views.py
> +from .models import *
import * 은 사용하지 않습니다. 각각 필요한 클래스만 지칭해서 import 해주세요

2020-07-02 17:33 UTC, soheon-lee commented on product/views.py
> +import json
```suggestion
import json

from django.views import View
from django.http import (
        JsonResponse, 
        HttpResponse
)

from .models import *
```

2020-07-02 17:36 UTC, soheon-lee commented on product/views.py
> +                                                                        ]
```suggestion
            product_info = dict()

            for item in product_detail:
                product_info = {
                    "sub_sub_category" : item.product.type_name.name,
                    "product_name"     = item.product.name
                    "product_price"    = int(item.product.price)
                    "product_guide"    = [guide for guide in item.product.guide.split(',')]
                    "product_color"]    = item.color.name
                    "product_color_id" = item.color.id
                    "product_size"     = [size for size in item.product.product_size.size.split(',')]
                    "button_colors"    = [colors.color.name for colors in ProductColor.objects.filter(
                                                                                product_id = item.product.id)]
                    "button_images"    = [button.color.button_color for button in ProductColor.objects.filter(
                                                                                            product_id = item.product.id)
                                                                                            ]
                    "product_images"   = [image.image_url for image in ProductImage.objects.filter(
                                                                        product_color = ProductColor.objects.get(
                                                                        color = Color.objects.get(id = item.color.id),
                                                                        product = Product.objects.get(
                                                                        id = item.product.id)
                                                                        ))
                                                                        ]
                     }
```

2020-07-02 17:43 UTC, soheon-lee commented on product/views.py
> +                                                                        ]
위에 생성하신 `product_info`와 마찬가지로 딕셔너리 내부에 바로 
```
product_info = {
    '키' : '밸류',
    '키' : '밸류'
}
```
형태로 선언하시면 빈 dict()를 선언하지 않아도 되어서 좋고, 키 앞에 딕셔너리 이름을 매번 지칭해주지 않아서 더 좋을 것 같습니다.

2020-07-03 02:06 UTC, soheon-lee commented
LGTM

2020-07-03 02:06 UTC, merged